server:
  replicas: 1
  service:
    type: ClusterIP
  extraArgs:
    - --insecure

configs:
  cm:
    timeout.reconciliation: 30s
    accounts.devops: apiKey,login

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, devops, role:admin

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: false

notifications:
  enabled: false