apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: infra-tools

spec:
  project: default

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 9.3.0

    helm:
      releaseName: grafana

      valuesObject:

        persistence:
          enabled: false

        service:
          type: ClusterIP
          port: 80

        resources:
          requests:
            cpu: 50m
            memory: 128Mi

          limits:
            cpu: 250m
            memory: 256Mi

        adminPassword: admin123

        datasources:
          datasources.yaml:
            apiVersion: 1

            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus-server.monitoring.svc.cluster.local
                isDefault: true

  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true