# ===== Builder stage =====
FROM python:3.9-slim AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libjpeg-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /install

COPY requirements.txt .
RUN pip install --prefix=/install --no-cache-dir -r requirements.txt


# ===== Runtime stage =====
FROM python:3.9-slim

# Мінімальні runtime-залежності для torch + pillow
RUN apt-get update && apt-get install -y --no-install-recommends \
    libjpeg62-turbo \
    libstdc++6 \
    libgcc-s1 \
    && rm -rf /var/lib/apt/lists/*

# Копіюємо python-пакети
COPY --from=builder /install /usr/local

WORKDIR /app

COPY model.pt inference.py .

CMD ["python", "inference.py"]
